name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build C++ library
        run: make
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: flagr-so
          path: pyflagr/pyflagr/flagr.so

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build C++ library
        run: make
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: flagr-dylib
          path: pyflagr/pyflagr/flagr.dylib

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build C++ library
        run: .\makefile.bat
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: flagr-dlls
          path: |
            pyflagr/pyflagr/flagr.dll
            pyflagr/pyflagr/libgcc_s_seh-1.dll
            pyflagr/pyflagr/libstdc++-6.dll

  release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: flagr-so
          path: pyflagr/pyflagr

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: flagr-dylib
          path: pyflagr/pyflagr

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: flagr-dlls
          path: pyflagr/pyflagr

      - name: Build Python package
        working-directory: ./pyflagr
        run: python setup.py sdist bdist_wheel

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pyflagr/dist/*
            pyflagr/pyflagr/flagr.so
            pyflagr/pyflagr/flagr.dylib
            pyflagr/pyflagr/flagr.dll
            pyflagr/pyflagr/libgcc_s_seh-1.dll
            pyflagr/pyflagr/libstdc++-6.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
